### ISSUE TITLE
Detailed user manuals required

### ISSUE THREAD

**Issue by Bobholamovic** [Z-Zheng/SimpleCV#145]
Excellent work from *RS-IDEA* :grin: Actually, considering all the well maintained codes and carefully designed data structures, I've noticed that the document appears no exhaustive, though concise enough. Hence, is it possible to add `Wiki` or some more detailed manuals for the convenience of users?

BTW, a dead link reported here: 
The link to `USAGE.md` in `README.md` actually directs to a `Not Found` page.

**Comment by Bobholamovic** [comment]
学长太强了 👍

**Comment by Z-Zheng** [comment]
Thanks very much for your attention and helpful advice.
In the future, we will release some projects, which can help users to use this package.
Hmmm, the document is a hard job but it is necessary.
Maybe I will find some assistants to complete it together as soon as possible. 

---------------

meiyou, meiyou, shi di qiang de bu xing!
