### ISSUE TITLE
About FarSeg

### ISSUE THREAD

**Issue by Luffy03** [Z-Zheng/SimpleCV#165]
Hello, you have really done a good job! Congratulation! And would you please open the code about the paper 'Foreground-Aware Relation Network for Geospatial Object Segmentation in High Spatial Resolution Remote Sensing Imagery'? I am quite interested about your work. Thank you very much!

**Comment by Z-Zheng** [comment]
Code has been available at https://github.com/Z-Zheng/FarSeg
